server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 9090

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    virtual-host: sample

## p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: false