server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 9090

spring:
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create # 공부용
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: sample

rabbitmq:
  queue:
    name: sample.queue
  exchange:
    name: sample.exchange
  routing:
    key: sample.queue

## p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: false

# logger
logging.level:
  org.hibernate.SQL: debug